# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Poets Pie
site_url: https://poetspie.com
nav:
    - Home: index.md
    - Basement Poems:
      - Steps in the Estonian bog: poetry/basement-period/steps-in-the-estonian-bog.md
      - Foggy Philadelphia: poetry/basement-period/foggy-philadelphia.md
      - Each frog sings to you: poetry/basement-period/each-frog-sings-to-you.md
      - A little bench for each artist: poetry/basement-period/a-little-bench-for-each-artist.md
      - Plastic Keys Touching my Fingers: poetry/basement-period/plastic-keys-touching-my-fingers.md
      - Cowboy themed buffet: poetry/basement-period/cowboy-themed-buffet.md
      - Ears Uncovered, Clouds that Hang: poetry/basement-period/ears-uncovered-clouds-that-hang.md
      - Baby Hiccups: poetry/basement-period/baby-hiccups.md
      - Library Doors: poetry/basement-period/library-doors.md
      - Cold Storage Poem: poetry/basement-period/cold-storage-poem.md
      - I felt something pure: poetry/basement-period/i-felt-something-pure.md
      - Early morning keystrokes: poetry/basement-period/early-morning-keystrokes.md
      - Hope rings real each morning: poetry/basement-period/hope-rings-real-each-morning.md
      - Today you might perish, you might flourish,: poetry/basement-period/today-you-might-perish-you-might-flourish.md
      - loop-hole in the universe: poetry/basement-period/loop-hole-in-the-universe.md
    - Probiotic Poems: 
      - Shave the hog’s ear: poetry/basement-period/shave-the-hogs-ear.md
      - Optimistic Rain Coming: poetry/probiotic-period/optimistic-rain-coming.md
      - 15-minute family: poetry/probiotic-period/15-minute-family.md
    - Stuffed Skunk Considers: 
      - Breeding: poetry/stuffed-skunk-considers/breeding.md
      - Babies Smile: poetry/stuffed-skunk-considers/babies-smile.md
      - The Stars: poetry/stuffed-skunk-considers/the-stars.md 
    - Stories:
      - Little Ones: stories/little-ones.md
      - Big Ones: stories/big-ones.md
    - Screenplays:
      - Swing Swing Swing: screenplays/swing-swing-swing.md

      
theme:
  name: material
  features:
    - navigation.tabs
    - toc.integrate
    - navigation.sections
extra:
  generator: false

markdown_extensions:
    - nl2br